### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'on_delete' 

### ISSUE THREAD

**Issue by t04st3r** [jose-lpa/django-tracking-analyzer#10]
I have this error after pip install when I try to apply migrations

`pip install django-tracking-analyzer`

`python manage.py migrate tracking_analyzer`

`Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/raffaele/PycharmProjects/my_website/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/raffaele/PycharmProjects/my_website/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/raffaele/PycharmProjects/my_website/venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/raffaele/PycharmProjects/my_website/venv/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/raffaele/PycharmProjects/my_website/venv/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/raffaele/PycharmProjects/my_website/venv/lib/python3.6/site-packages/tracking_analyzer/models.py", line 15, in <module>
    class Tracker(models.Model):
  File "/home/raffaele/PycharmProjects/my_website/venv/lib/python3.6/site-packages/tracking_analyzer/models.py", line 33, in Tracker
    content_type = models.ForeignKey(ContentType)
TypeError: __init__() missing 1 required positional argument: 'on_delete'`

I believe it is related to the fact that since Django 2.x, on_delete is required on ForeignKey()
[Docs](https://docs.djangoproject.com/en/2.1/releases/1.9/#foreignkey-and-onetoonefield-on-delete-argument)

**Comment by t04st3r** [comment]
Sorry already fixed on [cd0cbc5c9e81bb7baf8f4b75abf4af00330ddf96](https://github.com/jose-lpa/django-tracking-analyzer/pull/7)
